version: "3"

services:
  mysql:
    image: "mysql:8.0"
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABASE: science-quiz
      MYSQL_USER: rootuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    expose:
      - "3306"